### ISSUE TITLE
Playback stops

### ISSUE THREAD

**Issue by 3rpi** [jakubvalenta/video-pi#1]
Hi!
First of all, great project!
My issue is, that after some time, the playback stops.
I'm using a Raspberry Pi 3B+, a 16GB Sandisk microSD Card and a 32GB Sandisk flashdrive.
I had no problems during installation. Inserting the flashdrive it starts automatically.
I tried with diferent flashdrives, but the problem is the same.
I remount the drive and it works again, but after some time it stops again.

**Comment by 3rpi** [comment]
These error messages pop up in the terminal
Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573699] Internal error: Oops: 2817 [#2] SMP ARM

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573862] Process vlc (pid: 6829, stack limit = 0x0a68b0a6)

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573868] Stack: (0x9d6d7df8 to 0x9d6d8000)

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573874] 7de0:                                                       0000071f 00000000

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573883] 7e00: 9d6d7e44 9d6d7e10 8010bd8c 96156200 80a414c8 00000000 9d6d7e34 9d6d7e28

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573891] 7e20: 802c1a60 802c1980 9d6d7e7c 9d6d7e38 80657bec 00000001 9d6d7e6c 9d6d7e48

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573899] 7e40: 8021b93c 8021ca40 80da46c0 00000000 b654adc0 b6b686c0 80927a98 802ccc84

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573907] 7e60: 9d6d7ebc 802ccc9c 9fd666b8 80e04f88 9d6d7ea4 9d6d7e80 802ccc84 8011113c

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573916] 7e80: 35dc4000 3ea1675f b6578b40 715ae000 00000055 00000040 9d6d7f24 9d6d7ea8

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573924] 7ea0: 802c3170 802ccc10 00000001 80116138 b5797c00 80e04f88 9d6d7efc 7379c7e0

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573932] 7ec0: b5df9258 80044970 7379c7e0 acda46c0 0000000f 00000036 9d6d7f6c 9d6d7ee8

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573940] 7ee0: 8031df80 80658f80 9fd666b8 b6ffe26c 00000000 80e04f88 9d6d7f24 9d6d7fb0

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573949] 7f00: 715ae000 0000080f 9fd80f40 b5797c00 b5797c40 8092e134 9d6d7f74 9d6d7f28

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573957] 7f20: 8092e134 801784e0 8010d104 8032a93c 00000168 00000170 80044970 80e04f88

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573965] 7f40: 9d6d7f5c acda46c1 00000000 80044970 7379c7e0 acda46c0 0000000f 00000036

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573974] 7f60: 9d6d7f94 9d6d7f70 8031e414 8031dbbc 00000168 00000170 00000188 00000036

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573982] 7f80: 801011c4 9d6d6000 9d6d7fa4 9d6d7f98 8031e450 8031e3b4 00000000 9d6d7fa8

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573990] 7fa0: 80101000 8031e444 00000168 00000170 0000000f 80044970 7379c7e0 00000000

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.573998] 7fc0: 00000168 00000170 00000188 00000036 5e03000c 00010003 5a2cd200 71547000

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.574006] 7fe0: 67c69154 7379c7bc 5e0160c0 76e9c51c 68000010 0000000f 00000000 00000000

Message from syslogd@VideoPi at Dec  1 11:51:48 ...
 kernel:[ 4160.574123] Code: e3a02004 e1a02312 e2423001 e1c00003 (ee070f3e)

**Comment by jakubvalenta** [comment]
Hi, thanks for the bug report and the log output.

Can you scroll the terminal up (with mouse wheel or `SHIFT+PGUP`)? Maybe there's something that could clarify whether the crash happens with a particular file or always at the same time of the playback etc.

There is also another log file in `~/.local/share/video-pi/video-pi.log` that you can check. It contains info about USB connect/disconnect and playback start/stop.

**Comment by 3rpi** [comment]
I ssh into the pi and there is no other message in the terminal, i can't scroll up.
On startup this message shows up:
VLC media player 3.0.11 Vetinari (revision 3.0.11-0-gdc0c5ced72)
[000ef9e0] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
[00074b58] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
libEGL warning: DRI2: failed to authenticate
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
libEGL warning: DRI2: failed to authenticate
[73503828] mmal_xsplitter vout display error: Failed to open Xsplitter:opengles2 module

**Comment by 3rpi** [comment]
Behind the playback I get this erros message in a separate window:
"Your input can't be opened:
VLC is unable to open the MRL 'file:///media/ErpiDrive/System%20Volume%20Information/WPSettings.dat'. Check the log for details."
I can't delete SystemVolumeInformation folder.

**Comment by 3rpi** [comment]
This is in the video-pi.log file:
===========================================
Monitoring activity from the disks daemon. Press Ctrl+C to cancel.
===========================================
added:     /org/freedesktop/UDisks/devices/sda
===========================================
added:     /org/freedesktop/UDisks/devices/sda1
device: [/dev/sda1]
    systeminternal: [0]
    usage:          [filesystem]
    type:           [ntfs]
    label:          [ErpiDrive]
    ismounted:      [0]
    nopolicy:       [0]
    hasmedia:       [1]
    opticaldisc:    []
    numaudiotracks: []
    blank:          []
    media:          []
    partition:      [1]
devmon: /usr/bin/udevil --mount /dev/sda1 --mount-options "ro,noexec,nosuid,nodev,noatime"    # (ErpiDrive)
Mounted /dev/sda1 at /media/ErpiDrive
devmon: [exec on drive] eval video-pi-stop; lxterminal --geometry=120x40 -e video-pi-play "$point" &
omxiv: no process found
===========================================
changed:     /org/freedesktop/UDisks/devices/sda1
vlc: no process found
device: [/dev/sda1]
    systeminternal: [0]
    usage:          [filesystem]
    type:           [ntfs]
    label:          [ErpiDrive]
    ismounted:      [1]
    nopolicy:       [0]
    hasmedia:       [1]
    opticaldisc:    []
    numaudiotracks: []
    blank:          []
    media:          []
    partition:      [1]
===========================================
removed:   /org/freedesktop/UDisks/devices/sda1
devmon: /usr/bin/udevil --unmount /dev/sda1
devmon: [exec on remove] eval video-pi-stop &
omxiv: no process found
===========================================
removed:   /org/freedesktop/UDisks/devices/sda
vlc: no process found
devmon: /usr/bin/udevil clean
devmon: [exec on remove] eval video-pi-stop &
omxiv: no process found
vlc: no process found
===========================================
added:     /org/freedesktop/UDisks/devices/sda
===========================================
added:     /org/freedesktop/UDisks/devices/sda1
device: [/dev/sda1]
    systeminternal: [0]
    usage:          [filesystem]
    type:           [ntfs]
    label:          [ErpiDrive]
    ismounted:      [0]
    nopolicy:       [0]
    hasmedia:       [1]
    opticaldisc:    []
    numaudiotracks: []
    blank:          []
    media:          []
    partition:      [1]
devmon: /usr/bin/udevil --mount /dev/sda1 --mount-options "ro,noexec,nosuid,nodev,noatime"    # (ErpiDrive)
Mounted /dev/sda1 at /media/ErpiDrive
devmon: [exec on drive] eval video-pi-stop; lxterminal --geometry=120x40 -e video-pi-play "$point" &
omxiv: no process found
vlc: no process found
===========================================
changed:     /org/freedesktop/UDisks/devices/sda1
device: [/dev/sda1]
    systeminternal: [0]
    usage:          [filesystem]
    type:           [ntfs]
    label:          [ErpiDrive]
    ismounted:      [1]
    nopolicy:       [0]
    hasmedia:       [1]
    opticaldisc:    []
    numaudiotracks: []
    blank:          []
    media:          []
    partition:      [1]

(lxterminal:2816): Gtk-CRITICAL **: 09:20:58.406: gtk_widget_get_realized: assertion 'GTK_IS_WIDGET (widget)' failed

(lxterminal:2816): Gtk-CRITICAL **: 09:20:58.406: gtk_widget_get_realized: assertion 'GTK_IS_WIDGET (widget)' failed

(lxterminal:2816): Gtk-CRITICAL **: 09:20:58.406: gtk_widget_get_realized: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by jakubvalenta** [comment]
You can try adding `System Volume Information` or `System%20Volume%20Information` or maybe both to `/etc/video-pi.fdignore` and see if it helps

/etc/video-pi.fdignore:
```
$RECYCLE.BIN
*.db
*.ini
System Volume Information
System%20Volume%20Information
```

**Comment by 3rpi** [comment]
I added the folder both way, but after that VideoPi wouldn't start.
I added *.dat for ignoring the file. This way it started.
I'm testing now.

**Comment by 3rpi** [comment]
I got the same message in terminal.
This is everyting what I see in the terminal:

Linux VideoPi 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Dec  2 11:14:00 2020
pi@VideoPi:~ $ 
Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.770972] Internal error: Oops: 2817 [#1] SMP ARM

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771142] Process vlc (pid: 1352, stack limit = 0x8eb010f1)

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771148] Stack: (0xb4289df8 to 0xb428a000)

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771155] 9de0:                                                       0000071f 00000000

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771163] 9e00: 80ba9b30 00000004 b4289e3c a62fe400 80a414c8 00000000 b4289e34 b4289e28

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771171] 9e20: 802c1a60 802c1980 b4289e7c b4289e38 80657bec 00000001 8092d9e4 8021b8f0

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771180] 9e40: 80e10d40 00000000 b4289e84 b4289e58 80191a40 8092d99c 68000113 802ccc84

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771188] 9e60: b4289ebc 802ccc9c b57e35a0 80e04f88 b4289ea4 b4289e80 802ccc84 8011113c

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771196] 9e80: b645f000 3ea8475f a4d265a0 5bb68000 00000055 00000040 b4289f24 b4289ea8

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771205] 9ea0: 802c3170 802ccc10 00000001 80116138 a8d5f400 80e04f88 b4289efc 5dfeb7a0

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771213] 9ec0: b5df9258 80044970 5dfeb7a0 b40509c0 00000012 00000036 b4289f6c b4289ee8

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771221] 9ee0: 8031df80 80658f80 b57e35a0 b7309c00 00000000 80e04f88 b4289f24 b4289fb0

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771229] 9f00: 5bb68000 0000080f a62aeac0 a8d5f400 a8d5f440 8092e134 b4289f74 b4289f28

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771237] 9f20: 8092e134 801784e0 8010d104 8032a93c 00000168 00000170 80044970 80e04f88

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771246] 9f40: b4289f5c b40509c1 00000000 80044970 5dfeb7a0 b40509c0 00000012 00000036

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771254] 9f60: b4289f94 b4289f70 8031e414 8031dbbc 00000168 00000170 00000188 00000036

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771262] 9f80: 801011c4 b4288000 b4289fa4 b4289f98 8031e450 8031e3b4 00000000 b4289fa8

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771270] 9fa0: 80101000 8031e444 00000168 00000170 00000012 80044970 5dfeb7a0 00000000

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771278] 9fc0: 00000168 00000170 00000188 00000036 5bc0300c 00010003 5b1dbbc0 5bb01000

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771286] 9fe0: 68c38154 5dfeb77c 5bbe90c0 76dd651c 68000010 00000012 00000000 00000000

Message from syslogd@VideoPi at Dec  2 11:23:07 ...
 kernel:[  552.771406] Code: e3a02004 e1a02312 e2423001 e1c00003 (ee070f3e)

**Comment by 3rpi** [comment]
I did a reboot 2 hours ago and is working now.
I hope it will work fine.

**Comment by jakubvalenta** [comment]
I'm glad the issue is fine now. I've added `*.dat` to the ignore file in 39c76de7ce43f50d9907c2285a41fef995a2237e and published a new version of the `video-pi` package: https://github.com/jakubvalenta/video-pi/releases/tag/v1.2.0
