### ISSUE TITLE
Configuration goes in wrong directory

### ISSUE THREAD

**Issue by srw777** [jakubvalenta/video-pi#2]
Recent versions of Raspberry Pi OS allow the user to choose to create a custom username rather than simply using 'pi'.  The Video Pi installer doesn't recognise this and places the required config files in /home/pi.  The manual solution is simple... copy those files from /home/pi into your home directory.  It would be nice if the installer could recognise this and do the right thing.

**Comment by jakubvalenta** [comment]
Thanks for creating this issue. I will adjust the Debian package to put the config files in /usr/share instead of /home and then add a script or instructions that the user of the package will be advised to run. It will copy or symlink the files from /usr/share to /home.

**Comment by jakubvalenta** [comment]
Fixed in [v2.0.0](https://github.com/jakubvalenta/video-pi/releases/tag/v2.0.0). The Debian package doesn't install files into the home directory anymore. In only installs a command `video-pi-install`, which should be run as regular user after installation. See the updated README.
